---
title: "RAPID Open-ended Questions"
output: 
  html_document:
    toc: FALSE
    theme: flatly
    css: "custom.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

RAPID Open-ended Questions
This site contains responses to the open-ended questions collected as part of the project called Rapid Assessment of Pandemic Impact on Development in Early Childhood (RAPID-EC), launched by the University of Oregon's Center for Translational Neuroscience.
Use the navigation menu above to explore responses from:

Household Response Tables: Open-ended responses from caregivers and families
Provider Response Tables: Open-ended responses from childcare providers

Each table is searchable and filterable to help you find specific themes or responses.
Read more about our study here.
How to Use This Site

Select a population: Choose either "Household" or "Provider" from the navigation menu
Choose a question: Select from the dropdown menu of available questions
Search and filter: Use the search boxes and filters in each table to find specific responses
Export data: Use the buttons above each table to copy, download, or print the results

Last updated: r Sys.Date()