name: Build and Deploy RAPID Open Website

# Trigger the workflow when files are pushed to main branch
on:
  push:
    branches: [ main ]
    paths: 
      - 'data/**'
      - 'R/**'
      - '_*.Rmd'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'
        
    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2
      
    - name: Install R dependencies
      run: |
        install.packages("pak")
        pak::pkg_install(c("rmarkdown", "here", "haven", "tidyverse", 
                          "zoo", "DT", "lubridate", "yaml", "sjlabelled"))
      shell: Rscript {0}
      
    - name: Process data and build site
      run: |
        source("R/build-site.R")
      shell: Rscript {0}
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site