name: Build and Deploy RAPID Open Website

# Trigger the workflow when files are pushed to main branch
on:
  push:
    branches: [ main ]
    paths: 
      - 'data/**'
      - 'R/**'
      - '_*.Rmd'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'
        use-public-rspm: true  # Use pre-compiled binaries for faster installs
        
    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2
      
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION') }}-${{ hashFiles('renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-r-
      
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev
      
    - name: Install R dependencies
      run: |
        options(repos = c(CRAN = "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"))
        install.packages(c(
          "rmarkdown", 
          "here", 
          "haven", 
          "tidyverse",  
          "zoo", 
          "DT", 
          "lubridate", 
          "yaml",
          "htmltools"
        ))
      shell: Rscript {0}
      
    - name: Process data and build site
      run: |
        source("R/build-site.R")
      shell: Rscript {0}
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true